describe('Página Principal', () => {
  beforeEach( () => {
    cy.visit('http://localhost:3000/')
  })
  it('Deve renderizar a página corretamente!', () => {
    cy.getByData("titulo-principal").contains('Experimente mais liberdade no controle da sua vida financeira. Crie sua conta com a gente!')
    cy.getByData("conta").contains('Conta e cartão gratuitos')
    cy.getByData("saque").contains('Saques sem custo')
    cy.getByData("ponto").contains('Programa de pontos')
    cy.getByData("seguro").contains('Seguro Dispositivos')
    cy.getByData("div-principal1").should('be.visible')
    cy.getByData("div-secundária1").should('be.visible')
    cy.getByData("div-terciária1").should('be.visible')
    cy.getByData("imagem1").should('be.visible')
    cy.getByData("div-principal2").should('be.visible')
    cy.getByData("div-secundária2").should('be.visible')
    cy.getByData("div-terciária2").should('be.visible')
    cy.getByData("imagem2").should('be.visible')
    cy.getByData("parágrafo1").contains('Isso mesmo, nossa conta é digital, sem custo fixo e mais que isso: sem tarifa de manutenção.')
    cy.getByData("div-terciária3").should('be.visible')
    cy.getByData("imagem3").should('be.visible')
    cy.getByData("parágrafo2").contains('Você pode sacar gratuitamente 4x por mês de qualquer Banco 24h.')
    cy.getByData("div-terciária4").should('be.visible')
    cy.getByData("imagem4").should('be.visible')
    cy.getByData("parágrafo3").contains('Você pode acumular pontos com suas compras no crédito sem pagar mensalidade!')
    cy.getByData("div-terciária5").should('be.visible')
    cy.getByData("imagem5").should('be.visible')
    cy.getByData("parágrafo4").contains('Seus dispositivos móveis (computador e laptop) protegidos por uma mensalidade simbólica.')
//    cy.getByData('h1').contains('Experimente mais liberdade no controle da sua vida financeira. Crie sua conta com a gente!')
  })

  it('Deve renderizar os parágrafos corretamente!', () => {
    cy.verifyData('parágrafo1', 'Isso mesmo, nossa conta é digital, sem custo fixo e mais que isso: sem tarifa de manutenção.')
    cy.verifyData('parágrafo2', 'Você pode sacar gratuitamente 4x por mês de qualquer Banco 24h.')
    cy.verifyData('parágrafo3', 'Você pode acumular pontos com suas compras no crédito sem pagar mensalidade!')
    cy.verifyData('parágrafo4', 'Seus dispositivos móveis (computador e laptop) protegidos por uma mensalidade simbólica.')

  })
})